# Generated by Django 2.0.8 on 2018-12-07 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='質問')),
                ('FormType', models.IntegerField(choices=[(1, 'text'), (2, 'checkbox'), (3, 'radio'), (4, 'file'), (5, 'select'), (6, 'select-multiple'), (7, 'tel'), (8, 'url'), (9, 'email'), (10, 'datetime'), (11, 'date'), (12, 'month'), (13, 'week'), (14, 'time'), (15, 'datetime-local'), (16, 'number'), (17, 'image'), (18, 'range'), (19, 'color'), (20, 'reset'), (21, 'button'), (22, 'password'), (23, 'search'), (24, 'hidden'), (25, 'submit')], default=0, verbose_name='回答追加可否フラグ')),
                ('AnswerAddFlg', models.IntegerField(choices=[(0, '不可'), (1, '可')], default=0, verbose_name='回答追加可否フラグ')),
                ('Required', models.IntegerField(choices=[(0, '必須でない'), (1, '必須')], default=0, verbose_name='必須')),
                ('AnswerValues', models.TextField(verbose_name='回答選択肢')),
                ('Balloon', models.TextField(verbose_name='吹き出し')),
                ('ConditionFlg', models.IntegerField(choices=[(0, '条件なし'), (1, '条件に合致した場合、回答必須'), (2, '条件に合致した場合、回答不可')], default=0, verbose_name='回答条件設定')),
                ('ConfirmedId', models.TextField(verbose_name='条件に合致する回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QestionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublishFlg', models.IntegerField(choices=[(0, '不可'), (1, '可')], default=0, verbose_name='公開可否')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='qestion',
            name='qestionversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QestionVersion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='qestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Qestion'),
        ),
    ]
