# Generated by Django 2.0.8 on 2018-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='confirmed_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='回答条件確認先質問ID'),
        ),
    ]
