# Generated by Django 2.0.8 on 2018-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20181213_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='system_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='システムID'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='system_name',
            field=models.TextField(blank=True, verbose_name='システム名'),
        ),
    ]
