# Generated by Django 2.0.8 on 2018-12-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20181213_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, verbose_name='回答'),
        ),
    ]
