# Generated by Django 2.0.8 on 2018-12-18 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(blank=True, verbose_name='カテゴリー名')),
                ('category_desc', models.TextField(blank=True, verbose_name='カテゴリー説明')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.TextField(blank=True, verbose_name='システム名')),
                ('system_id', models.CharField(blank=True, max_length=100, verbose_name='システムID')),
                ('diag_when', models.DateField(blank=True, verbose_name='診断月')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorymaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.CategoryMaster')),
                ('diagnosismaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.DiagnosisMaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(blank=True, verbose_name='質問')),
                ('form_type', models.IntegerField(blank=True, choices=[(1, 'text'), (2, 'checkbox'), (3, 'radio'), (4, 'file'), (5, 'select'), (6, 'select-multiple'), (7, 'tel'), (8, 'url'), (9, 'email'), (10, 'datetime'), (11, 'date'), (12, 'month'), (13, 'week'), (14, 'time'), (15, 'datetime-local'), (16, 'number'), (17, 'image'), (18, 'range'), (19, 'color'), (20, 'reset'), (21, 'button'), (22, 'password'), (23, 'search'), (24, 'hidden'), (25, 'submit')], default=0, verbose_name='回答タイプ')),
                ('answeradd_flg', models.IntegerField(blank=True, choices=[(0, '不可'), (1, '可')], default=0, verbose_name='回答追加可否フラグ')),
                ('required_flg', models.IntegerField(blank=True, choices=[(0, '必須でない'), (1, '必須')], default=0, verbose_name='必須')),
                ('answer_values', models.TextField(blank=True, verbose_name='回答選択肢')),
                ('balloon', models.TextField(blank=True, verbose_name='吹き出し')),
                ('condition_flg', models.IntegerField(blank=True, choices=[(0, '条件なし'), (1, '条件に合致した場合、回答必須'), (2, '条件に合致した場合、回答不可')], default=0, verbose_name='回答条件設定')),
                ('confirmed_id', models.IntegerField(blank=True, default=0, verbose_name='回答条件確認先質問ID')),
                ('confirmed_value', models.TextField(blank=True, verbose_name='条件に合致する回答')),
                ('disp_order', models.IntegerField(blank=True, default=0, verbose_name='表示順')),
                ('parent_id', models.IntegerField(blank=True, default=0, verbose_name='親となる質問のID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorymaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.CategoryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVersionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_flg', models.IntegerField(choices=[(0, '不可'), (1, '可')], default=0, verbose_name='公開可否')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.QuestionMaster'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionversionmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.QuestionVersionMaster'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='questionversionmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.QuestionVersionMaster'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.Question'),
        ),
    ]
