# Generated by Django 2.0.8 on 2018-12-22 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorymaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.CategoryMaster')),
                ('diagnosismaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.DiagnosisMaster')),
                ('questionmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.QuestionMaster')),
                ('questionversionmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.QuestionVersionMaster')),
            ],
        ),
    ]
