# Generated by Django 2.0.8 on 2018-12-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0002_auto_20181227_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmaster',
            name='set_answer_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='セットで回答する場合の回答数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaster',
            name='set_answer_flg',
            field=models.IntegerField(blank=True, choices=[(0, 'セットで回答しない'), (1, 'セットで回答する')], default=0, verbose_name='セットで回答するかどうか'),
        ),
        migrations.AddField(
            model_name='questionmaster',
            name='set_answer_values',
            field=models.TextField(blank=True, verbose_name='セットで回答する場合の項目名の種類'),
        ),
    ]
