# Generated by Django 2.0.8 on 2018-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0003_auto_20181228_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmaster',
            name='form_type',
            field=models.IntegerField(blank=True, choices=[(1, 'text'), (2, 'checkbox'), (3, 'radio'), (4, 'file'), (5, 'select'), (6, 'select-multiple'), (7, 'tel'), (8, 'url'), (9, 'email'), (10, 'datetime'), (11, 'date'), (12, 'month'), (13, 'week'), (14, 'time'), (15, 'datetime-local'), (16, 'number'), (17, 'image'), (18, 'range'), (19, 'color'), (20, 'reset'), (21, 'button'), (22, 'password'), (23, 'search'), (24, 'hidden'), (25, 'submit'), (26, 'text-set')], default=0, verbose_name='回答タイプ'),
        ),
    ]
